### ISSUE TITLE
Add new email-id for sending out confirmations

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/Car-Pool#10]
The email id used currently in proj/settings.py has been blocked. Create a new one and keeps its id password out of the main files (preferably create a json file) and add the json file to gitignore, so that no one has access to that email id.. and only admins know it.

**Comment by vsvipul** [comment]
@kpbot add "good first issue" "help wanted"

**Comment by Varunvaruns9** [comment]
Closed as a duplicate of #12
