### ISSUE TITLE
Paid rides with amount 0 should be considered as free.

### ISSUE THREAD

**Issue by dipanshu231099** [KamandPrompt/Car-Pool#16]
right now if a person unticks paid trip(that is when a ride is added) the search doesn't output this trip if free is not ticked on the dashboard which actually should have been shown. What is meant that free tickde should show only those rides which have amount 0(even if adder clicked paid and then kept the amount as 0). otherwise all possible options of the day should be shown.

**Comment by dipanshu231099** [comment]
@vsvipul @Varunvaruns9 please see if the issue is valid or not and if it is kindly add tags to it.

**Comment by devprajapat02** [comment]
@kpbot claim

**Comment by dipanshu231099** [comment]
Issue closed. Thanks @devprajapat02 for the changes
