### ISSUE TITLE
Use calendar widget for selecting date and time.

### ISSUE THREAD

**Issue by vsvipul** [KamandPrompt/Car-Pool#4]
Currently, we have to use 3 drop-downs in filter ride,
![screenshot 2019-01-20 at 1 40 35 pm](https://user-images.githubusercontent.com/29421208/51436760-42fe4b80-1cb9-11e9-8eb9-ce0faed69351.png)
and give the date and time in specified format in Add Ride form,
![screenshot 2019-01-20 at 1 40 47 pm](https://user-images.githubusercontent.com/29421208/51436767-645f3780-1cb9-11e9-8f0c-c8d04eca9056.png)

Instead we would want to have a calendar widget send the data to backend in the required format.

**Comment by vsvipul** [comment]
@kpbot add "good first issue" "help wanted"

**Comment by vsvipul** [comment]
@kpbot add "good first issue" "help wanted"

**Comment by Varunvaruns9** [comment]
Implementation wise there can be many ways to do this-
The cleanest and easiest would probably be to add a class to date/time input using widget parameter of form field and use any js datepicker widget to render a calendar that returns the date/time in required format to django.

**Comment by dipanshu231099** [comment]
https://eonasdan.github.io/bootstrap-datetimepicker/ iska view mode kaisa hai?

**Comment by Varunvaruns9** [comment]
Looks fine to me. You can start working on this :)

**Comment by dipanshu231099** [comment]
@kpbot assign

**Comment by dipanshu231099** [comment]
@kpbot claim

**Comment by dipanshu231099** [comment]
the form is being generated by django?

**Comment by Varunvaruns9** [comment]
Yup.

**Comment by dipanshu231099** [comment]
doubt: presently what i have done is that i have created a widgets.py as per this site https://simpleisbetterthancomplex.com/tutorial/2019/01/03/how-to-use-date-picker-with-django.html. also i have made my template directly in carpool/templates/bootstrap_datepicker.html the app runs and a new type of box is rendered but its calendar erc. is not working... is anything wrong?

**Comment by dipanshu231099** [comment]
edit to previous doubt i have added the following links to index.html <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />

**Comment by dipanshu231099** [comment]
which bootstrap we are using?

**Comment by vsvipul** [comment]
@dipanshu231099 
https://github.com/KamandPrompt/Car-Pool/blob/8141d784db191b9e78109055e8c1f75bdce006d0/carpool/static/js/bootstrap.js#L2

**Comment by dipanshu231099** [comment]
![Screenshot from 2019-07-02 21-23-39](https://user-images.githubusercontent.com/43211840/60529321-fad95f80-9d13-11e9-96cb-6283ec4bc5f2.png)
I'm getting this issue with widget formatting
the following is the type of format
![Screenshot from 2019-07-02 21-52-34](https://user-images.githubusercontent.com/43211840/60529380-13e21080-9d14-11e9-80d9-75e563ab133d.png)
